language: php

php:
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpunit ./tests/
  - php -f demo/aegean.php ATH PRG $(date -d 'next month' +%Y-%m-25) $(date -d 'next month' +%Y-%m-27) --table
